// frontend/src/utils/masterFallbackData.ts
import type { ScholarRegistryRecord } from '../api/registry';

export const DEFAULT_FALLBACK_SCHOLARS_RAW: ScholarRegistryRecord[] = [
  {
    id: 1,
    student_id: '2024-00192',
    full_name: 'Maria Santos',
    email: 'maria.santos@qc.edu.ph',
    school: 'Quezon City University (QCU)',
    program_id: 'tertiary-academic',
    program_name: 'Dean’s Tech Excellence Award (QCYDO Merit Grant)',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '2 Years, 1 Month',
    gwa: 1.75,
    units_enrolled: 18,
    status: 'Active Good Standing',
    grant_amount: 15000,
    disbursement_status: 'Disbursed',
    barangay: 'Barangay Batasan Hills, Quezon City',
    department: 'College of Computer Studies (CCS)',
    year_level: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
    phone: '+63 917 123 4567',
    address: 'Block 12 Lot 4, Batasan Hills, Quezon City',
    district: 'District 2',
    application_code: 'APP-QC-2026-2024-00192'
  },
  {
    id: 2,
    student_id: '2024-00841',
    full_name: 'Juan Dela Cruz',
    email: 'juan.delacruz@bcp.edu.ph',
    school: 'Bestlink College of the Philippines (BCP)',
    program_id: 'tertiary-economic',
    program_name: 'Economic Scholarship (Need-Based Tertiary)',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '1 Year, 4 Months',
    gwa: 1.85,
    units_enrolled: 21,
    status: 'Active Good Standing',
    grant_amount: 10000,
    disbursement_status: 'Disbursed',
    barangay: 'Barangay Novaliches Proper, Quezon City',
    department: 'College of Information Technology',
    year_level: '2nd Year',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=250&q=80',
    phone: '+63 918 234 5678',
    address: '14 Quirino Highway, Novaliches, Quezon City',
    district: 'District 5',
    application_code: 'APP-QC-2026-2024-00841'
  },
  {
    id: 3,
    student_id: '2024-01205',
    full_name: 'Angelica Reyes',
    email: 'angelica.reyes@qcu.edu.ph',
    school: 'Quezon City University (QCU)',
    program_id: 'tertiary-excel',
    program_name: 'QC Excel Scholarship (Tertiary STEM)',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '2 Years, 1 Month',
    gwa: 1.25,
    units_enrolled: 21,
    status: 'Active Good Standing',
    grant_amount: 80000,
    disbursement_status: 'Scheduled',
    barangay: 'Barangay Commonwealth, Quezon City',
    department: 'College of Engineering & Computer Studies',
    year_level: '3rd Year',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=250&q=80',
    phone: '+63 919 345 6789',
    address: '88 Commonwealth Ave, Quezon City',
    district: 'District 2',
    application_code: 'APP-QC-2026-2024-01205'
  },
  {
    id: 4,
    student_id: '2024-03412',
    full_name: 'Christian Gonzales',
    email: 'c.gonzales@stclaire.edu.ph',
    school: 'St. Claire College of Caloocan',
    program_id: 'tertiary-academic',
    program_name: 'Academic Scholarship (Tertiary College)',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '3 Years, 2 Months',
    gwa: 1.50,
    units_enrolled: 18,
    status: 'Active Good Standing',
    grant_amount: 52500,
    disbursement_status: 'Disbursed',
    barangay: 'Barangay Fairview, Quezon City',
    department: 'Department of Business Administration',
    year_level: '4th Year',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=250&q=80',
    phone: '+63 920 456 7890',
    address: '45 Regalado Ave, Fairview, Quezon City',
    district: 'District 5',
    application_code: 'APP-QC-2026-2024-03412'
  },
  {
    id: 5,
    student_id: '2024-04981',
    full_name: 'Beatrice Alonzo',
    email: 'beatrice.a@bcp.edu.ph',
    school: 'Bestlink College of the Philippines (BCP)',
    program_id: 'shs-academic',
    program_name: 'Academic Scholarship (Senior High School)',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '6 Months',
    gwa: 1.40,
    units_enrolled: 15,
    status: 'Active - Renewal Processing',
    grant_amount: 15000,
    disbursement_status: 'Scheduled',
    barangay: 'Barangay Holy Spirit, Quezon City',
    department: 'STEM Senior High Track',
    year_level: 'Grade 12',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=250&q=80',
    phone: '+63 921 567 8901',
    address: '102 Holy Spirit Drive, Quezon City',
    district: 'District 2',
    application_code: 'APP-QC-2026-2024-04981'
  },
  {
    id: 6,
    student_id: '2024-05120',
    full_name: 'Mark Joseph Torres',
    email: 'mark.torres@qcu.edu.ph',
    school: 'Quezon City University (QCU)',
    program_id: 'tertiary-filipino',
    program_name: 'Manuel L. Quezon Filipino Language & Literature Grant',
    current_term: '1st Semester AY 2026-2027',
    scholarship_age: '1 Year, 2 Months',
    gwa: 1.65,
    units_enrolled: 18,
    status: 'Active Good Standing',
    grant_amount: 52500,
    disbursement_status: 'Disbursed',
    barangay: 'Barangay San Bartolome, Quezon City',
    department: 'College of Education & Humanities',
    year_level: '2nd Year',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=250&q=80',
    phone: '+63 922 678 9012',
    address: '67 Quirino Highway, San Bartolome, Quezon City',
    district: 'District 5',
    application_code: 'APP-QC-2026-2024-05120'
  }
];
